name: whatsapp_analysis
description: Whatsapp group chat dashboard with Flutter.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^6.0.0
  path_provider: ^2.1.1
  flutter_emoji: ^2.5.1
  fl_chart: ^0.64.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.1

flutter:
  uses-material-design: true
